version: "3"
services:
  grass:
    build: 
      context: .
    volumes: 
      - ./src:/shared
      - ./Penaguila:/home/ubuntu/grassdata/Penaguila
    ports:
      - "127.0.0.1:6080:6080"
    environment:
      PASSWORD: medland
