version: "3"
services:
  grass:
    build: 
      context: .
    volumes: 
      - ./downloads:/home/ubuntu/downloads
      - ./src:/shared
      - ./grassdata:/home/ubuntu/grassdata
    ports:
      - "127.0.0.1:6080:6080"
    environment:
      PASSWORD: medland
